# Generated by Django 4.2.3 on 2023-11-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
