# Generated by Django 4.2.3 on 2023-11-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
